CREATE PROCEDURE LISTAR_CLIENTES
AS 
BEGIN
SELECT C.NOME NOME, C.CPF CPF, C.SEXO SEXO, T.DESCRICAO TIPO_CLIENTE, 
	S.DESCRICAO SITUACAO_CLIENTE 
FROM TB_CLIENTES C
INNER JOIN TB_TIPO_CLIENTE T
ON T.ID = C.TIPO_CLIENTE
INNER JOIN TB_SITUACAO_CLIENTE S
ON S.ID = C.SITUACAO_CLIENTE
END

CREATE PROCEDURE BUSCA_CLIENTE_POR_CPF
@CPF VARCHAR(14)
AS
BEGIN
SELECT * FROM TB_CLIENTES WHERE CPF = @CPF
END

CREATE PROCEDURE LISTA_TIPO_CLIENTE
AS
BEGIN
SELECT * FROM TB_TIPO_CLIENTE
END

CREATE PROCEDURE LISTA_SITUACAO_CLIENTE
AS
BEGIN
SELECT * FROM TB_SITUACAO_CLIENTE
END

CREATE PROCEDURE NOVO_CLIENTE
@Cpf varchar(14),
@Nome varchar(200),
@Situacao_Cliente int,
@Tipo_Cliente int,
@Sexo char
AS
BEGIN
INSERT INTO TB_CLIENTES(CPF, NOME, SITUACAO_CLIENTE, TIPO_CLIENTE, SEXO)
VALUES(@Cpf, @Nome, @Situacao_Cliente,@Tipo_Cliente,@Sexo)
END

CREATE PROCEDURE ATUALIZA_CLIENTE
@Cpf varchar(14),
@Nome varchar(200),
@Situacao_Cliente int,
@Tipo_Cliente int,
@Sexo char
AS
BEGIN
UPDATE TB_CLIENTES 
SET 
NOME = @Nome,
SITUACAO_CLIENTE = @Situacao_Cliente,
TIPO_CLIENTE = @Tipo_Cliente,
SEXO = @Sexo
WHERE CPF = @Cpf
END

CREATE PROCEDURE REMOVE_CLIENTE
@Cpf VARCHAR(14)
AS
BEGIN
DELETE TB_CLIENTES WHERE CPF = @Cpf
END

