CREATE TABLE TB_TIPO_CLIENTE(
ID INT NOT NULL,
DESCRICAO VARCHAR(100) NOT NULL,
CONSTRAINT PK_TIPO_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE TB_SITUACAO_CLIENTE(
ID INT NOT NULL,
DESCRICAO VARCHAR(100) NOT NULL,
CONSTRAINT PK_SITUACAO_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE TB_CLIENTES(
CPF VARCHAR(14)  NOT NULL,
NOME VARCHAR(150) NOT NULL,
TIPO_CLIENTE INT NOT NULL,
SEXO CHAR NOT NULL,
SITUACAO_CLIENTE INT NOT NULL
CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF),
CONSTRAINT FK_CLIENTE_TIPO FOREIGN KEY (TIPO_CLIENTE) REFERENCES TB_TIPO_CLIENTE (ID),
CONSTRAINT FK_CLIENTE_SITUACAO FOREIGN KEY (SITUACAO_CLIENTE) REFERENCES TB_SITUACAO_CLIENTE (ID)
);